# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "supabase-action-example"

[db]
# Port to use for the local database URL.
port = 5432
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15


[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"




