name: 'backup-database'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually trigger the workflow'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Diagnostic Info
        run: echo "supabase_db_url: $supabase_db_url"
      - name: Backup roles
        run: supabase db dump --db-url "$supabase_db_url" -f roles.sql --role-only --debug
      - name: Backup schema
        run: supabase db dump --db-url "$supabase_db_url" -f schema.sql
      - name: Backup data
        run: supabase db dump --db-url "$supabase_db_url" -f data.sql --data-only --use-copy

