name: 'backup-database'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually trigger the workflow'
        required: false

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Supabase CLI
        run: |
          npm install -g @supabase/cli
          supabase init

      - name: Backup Roles
        run: |
          supabase db dump --role-only -f roles.sql

      - name: Backup Schema
        run: |
          supabase db dump -f schema.sql

      - name: Backup Data
        run: |
          supabase db dump --data-only --use-copy -f data.sql

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backup
          path: roles.sql, schema.sql, data.sql

